---
# handlers file for anaconda
- name: restart anaconda
  service:
    name: "{{ anaconda_service }}"
    state: restarted
  when:
    - ansible_virtualization_type != "docker" or anaconda_ignore_docker
