---
# handlers file for anaconda
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when:
    - ansible_virtualization_type != "docker"

- name: restart jupyter-notebook
  service:
    name: jupyter-notebook
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
