---
# handlers file for anaconda
- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  when:
    - ansible_virtualization_type != "docker"

- name: restart anaconda
  service:
    name: anaconda
    state: restarted
  when:
    - ansible_virtualization_type != "docker"
