---
dependency:
  name: galaxy
  options:
    role-file: requirements.yml
driver:
  name: vagrant
  provider:
    name: virtualbox
lint:
  name: yamllint
platforms:
  - name: anaconda-debian
    box: debian/stretch64
  - name: anaconda-fedora
    box: fedora/29-cloud-base
provisioner:
  name: ansible
  lint:
    name: ansible-lint
scenario:
  name: vagrant
